'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MasterData
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''New_BTN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents New_BTN As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Consultant_List control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Consultant_List As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''Details_PNL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Details_PNL As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''FirstName_txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FirstName_txt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LastName_txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LastName_txt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''NETID_txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NETID_txt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''GenNETID_BTN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GenNETID_BTN As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''eMail_txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eMail_txt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Dept_List control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dept_List As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Sup_List control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Sup_List As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Position_txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Position_txt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Location_LST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Location_LST As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Office_txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Office_txt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''PhoneExtention_txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PhoneExtention_txt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DIV_LST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DIV_LST As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Unit_LST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Unit_LST As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''AD_txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AD_txt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Service_Req_txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Service_Req_txt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Company_txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Company_txt As Global.System.Web.UI.WebControls.TextBox
End Class
